include:
  - path: './debug-dev.yml'
    relativePath: true
  - path: './release-dev.yml'
    relativePath: true
  - path: './profile-dev.yml'
    relativePath: true
  - path: './debug-prd.yml'
    relativePath: true
  - path: './profile-prd.yml'
    relativePath: true
  - path: './release-prd.yml'
    relativePath: true
  - path: './debug.yml'
    relativePath: true
  - path: './profile.yml'
    relativePath: true
  - path: './release.yml'
    relativePath: true

settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: NO
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    CLANG_ANALYZER_NONNULL: YES
    CLANG_CXX_LANGUAGE_STANDARD: 'gnu++0x'
    CLANG_CXX_LIBRARY: 'libc++'
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    'CODE_SIGN_IDENTITY[sdk=iphoneos*]': 'iPhone Developer'
    COPY_PHASE_STRIP: NO
    ENABLE_STRICT_OBJC_MSGSEND: YES
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    GCC_C_LANGUAGE_STANDARD: gnu99
    GCC_NO_COMMON_BLOCKS: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    SDKROOT: iphoneos
    TARGETED_DEVICE_FAMILY: '1,2'
